from .undp_global import UndpGlobalScraper
from .africa import UndpAfricaScraper
from .arab import UndpArabStatesScraper
from .asia import UndpAsiaAndThePacificScraper
from .europe import UndpEuropeAndTheCommonwealthOfIndependentStatesScraper
from .latin_america import UndpLatinAmericaAndTheCaribbeanScraper
